# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 200
checkpoint_frequency: 30
batch_size: 6 # previous 32
dropout: 0.0
learning_rate: 0.0004
weight_decay: 0.01
lr_decay: 0.98
probability: 0.99999
mask_view: False
probability: 0.1

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
is_freeze: True

# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [EGOBODY]
dt_file: h36m_sh_conf_cam_source_final.pkl 
clip_len: 243
data_stride: 81
rootrel: False  # change
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0
lambda_lg: 0
lambda_a: 0
lambda_av: 0
lambda_mv: 0  # new

# Augmentation
synthetic: False
flip: True # True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
